# SwiftLint Configuration for CultureLens iOS
# https://github.com/realm/SwiftLint

# Paths to include
included:
  - CultureLens

# Paths to exclude
excluded:
  - CultureLens/Resources
  - .build
  - DerivedData

# Rule configuration
disabled_rules:
  - trailing_whitespace # Can be annoying in multiline strings
  - line_length # SwiftUI views often have long lines
  - type_body_length # SwiftUI views can be large
  - file_length # Single-file views are common in SwiftUI

opt_in_rules:
  - array_init
  - attributes
  - closure_end_indentation
  - closure_spacing
  - collection_alignment
  - contains_over_filter_count
  - contains_over_filter_is_empty
  - contains_over_first_not_nil
  - contains_over_range_nil_comparison
  - discouraged_object_literal
  - empty_collection_literal
  - empty_count
  - empty_string
  - enum_case_associated_values_count
  - explicit_init
  - extension_access_modifier
  - fallthrough
  - fatal_error_message
  - first_where
  - flatmap_over_map_reduce
  - identical_operands
  - implicit_return
  - joined_default_parameter
  - last_where
  - legacy_multiple
  - legacy_random
  - literal_expression_end_indentation
  - modifier_order
  - multiline_arguments
  - multiline_function_chains
  - multiline_literal_brackets
  - multiline_parameters
  - number_separator
  - operator_usage_whitespace
  - overridden_super_call
  - prefer_self_type_over_type_of_self
  - prefer_zero_over_explicit_init
  - private_action
  - private_outlet
  - prohibited_super_call
  - redundant_nil_coalescing
  - redundant_type_annotation
  - single_test_class
  - sorted_first_last
  - sorted_imports
  - static_operator
  - toggle_bool
  - unavailable_function
  - unneeded_parentheses_in_closure_argument
  - unowned_variable_capture
  - untyped_error_in_catch
  - vertical_parameter_alignment_on_call
  - vertical_whitespace_closing_braces
  - vertical_whitespace_opening_braces
  - yoda_condition

# Custom rule configurations
identifier_name:
  min_length:
    warning: 2
    error: 1
  max_length:
    warning: 50
    error: 60
  excluded:
    - id
    - x
    - y
    - i
    - j
    - ok
    - to
    - ms
    - A
    - B

function_body_length:
  warning: 60
  error: 100

function_parameter_count:
  warning: 8
  error: 10

nesting:
  type_level:
    warning: 3
    error: 5
  function_level:
    warning: 5
    error: 8

cyclomatic_complexity:
  warning: 15
  error: 25

large_tuple:
  warning: 4
  error: 5

force_cast:
  severity: warning

force_try:
  severity: warning

force_unwrapping:
  severity: warning

# SwiftUI-specific adjustments
vertical_whitespace:
  max_empty_lines: 2

trailing_comma:
  mandatory_comma: true

# Reporter type (xcode, json, csv, checkstyle, codeclimate, junit, html, emoji, sonarqube, markdown, github-actions-logging)
reporter: "xcode"
