name: Bug Report
description: Something is broken
title: "bug: "
labels: ["bug"]
body:
  - type: textarea
    id: description
    attributes:
      label: What's Broken
      description: Describe what's happening
      placeholder: When I click X, Y happens instead of Z...
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What should happen instead
    validations:
      required: true
  - type: textarea
    id: repro
    attributes:
      label: Steps to Reproduce
      description: How can we recreate this?
      value: |
        1.
        2.
        3.
    validations:
      required: true
  - type: dropdown
    id: area
    attributes:
      label: Area
      options:
        - Frontend
        - Backend
        - Firebase
        - Infra
    validations:
      required: true
  - type: dropdown
    id: priority
    attributes:
      label: Priority
      options:
        - High — Blocks progress
        - Medium — Should fix soon
        - Low — Nice to have
    validations:
      required: true
  - type: textarea
    id: screenshot
    attributes:
      label: Screenshot
      description: If applicable, add a screenshot
